### PR TITLE
Fix and improve rqlite intro

### PR DESCRIPTION
**Pull request by fern4lvarez**
Beside of typos or rewordings, some of the paragraphs were too long
and hard to read. Splitting them up and adding headers would improve
readability.

### CODE REVIEW

**Comment by mkorszun** [comment]
@fern4lvarez I like it. Ready to merge?

**Comment by fern4lvarez** [comment]
I think @Liz0 wanted to take a look during the day. Let's wait for her feedback.

**Comment by fern4lvarez** [comment]
Ready to merge!

**Comment by Liz0** [comment]
The changes are good. I would have a few additions but I can do this after the PR is merged.

**Pull request merged**
